name: Build

on:
  - pull_request

jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3.0.0
      - name: Unit Test
        run: |
          go build .
          go test ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4.4.0
        with:
          distribution: goreleaser
          version: latest
          args: release --skip-publish --rm-dist --snapshot
